spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mt?useUnicode=true&character_set_server=utf8mb4
    username: root
    password: 123456
    hikari:
      connection-init-sql: SET NAMES 'utf8mb4'



mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    local-cache-scope: session
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:/sqlmap/*.xml